### ISSUE TITLE
Connection issue 

### ISSUE THREAD

**Issue by Nyxx805** [RecklessBoon/Macro-Deck-Discord-Plugin#11]
For the life of me i cannot get it 2 connect 2 discord never ask for permission iv tried everything i know. plz help

**Comment by DodecaDev-LLC** [comment]
Can you provide more information:

- What version of Macro Deck you are using?
- What version of Discord you are using?
- Have you set up the Discord Application as per the documentation/video tutorial?
   - Have you tried deleting and starting from scratch?
- Have you entered the client id and secret in Macro Deck?
- Have you restarted Macro Deck?
