### ISSUE TITLE
Variable self

### ISSUE THREAD

**Issue by mrbean27123** [RecklessBoon/Macro-Deck-Discord-Plugin#12]
when my friend turns off the microphone or sound, my "self" variable changes. You can see this in the first picture, where I'm unmuted, but the variables say otherwise.
![1](https://github.com/RecklessBoon/Macro-Deck-Discord-Plugin/assets/124227232/35ada17f-f5d1-43d4-8518-c83e39048bf4)
![2](https://github.com/RecklessBoon/Macro-Deck-Discord-Plugin/assets/124227232/acf92fe4-a337-425f-8d3e-0c563d09ddc4)
![3](https://github.com/RecklessBoon/Macro-Deck-Discord-Plugin/assets/124227232/ec0994de-df38-4d41-b9b7-642a1d8c70e9)

**Comment by ReqwiemG** [comment]
I also encountered a problem
