### ISSUE TITLE
Rejected Auth, ERROR from RPC, and Invalid Scope

### ISSUE THREAD

**Issue by SquibsLand** [RecklessBoon/Macro-Deck-Discord-Plugin#16]
Hello, I would like to start by saying that I am likely doing something wrong here so any assistance will be greatly appreciated.

I am receiving the following errors after attempting to connect.
![image](https://github.com/user-attachments/assets/3ec398e2-2276-41cb-aa59-c4fd44704ee7)
![image](https://github.com/user-attachments/assets/beaf1aa8-d3c6-49fc-be51-1490494c900f)
![image](https://github.com/user-attachments/assets/5aea76c2-e32d-489a-a0fb-ec05fc8d00fb)

## Steps
These are the following steps that I am doing
1. Set client ID and Secret
![image](https://github.com/user-attachments/assets/49d3b3bc-aa13-491c-b163-88c12836468a)
2. Press the discord icon in Macro Deck
3.  Press Authorize in Discord
![image](https://github.com/user-attachments/assets/b7595566-6f3a-4fbb-89ef-ca7ee51837cc)

After doing so I received the errors I mentioned. 

As far as I can tell this should be correct bellow.
![image](https://github.com/user-attachments/assets/4abf696b-6b75-4b37-86af-804a1822cf88)

If you need anything else please let me know, thank you in advance for your assistance.

(Note: this post was edited because it was posted accidentally before completion)

**Comment by DodecaDev-LLC** [comment]
Have you tried deleting your discord application in the developer portal and recreating it following the steps here exactly? https://youtu.be/alSlrnzx-M8

**Comment by SquibsLand** [comment]
Yes I have, unless I missed something these are the steps I did:
1. Create an Application
2. Set a redirect for `https://127.0.0.1`
3. Copy the Client ID and Client Secret
4. Adjust the config to use the ID and Secret

Is there anything else I need to do?

**Comment by SquibsLand** [comment]
I have found out the issue! After a long time of testing and trying to get it to work, I went to the documentation for RPC: [https://discord.com/developers/docs/topics/rpc#rpc](https://discord.com/developers/docs/topics/rpc#rpc), and it appears that RPC is now in private beta. Luckily I have been a developer for many years and when I used one of my old applications and set it up with the same information it worked first try! 
![image](https://github.com/user-attachments/assets/cf9a9bc1-6937-431f-a2e6-3472f1ab10ac)
