### ISSUE TITLE
Infinite connection retries if MacroDeck is started before Discord

### ISSUE THREAD

**Issue by zedalert** [RecklessBoon/Macro-Deck-Discord-Plugin#2]
I noticed when MacroDeck is launched from autostart and Discord manually later, plugin can't connect to Discord until I manually reconnect it in the MacroDeck by clicking on the plugin icon.

**Comment by RecklessBoon** [comment]
I will look into this. Thanks for the feedback!

**Comment by RecklessBoon** [comment]
I have tried many different ways but I am unable to replicate this issue. If you do not have the latest version please update the latest version via the package manager in Macro Deck 2.

I plan on switching the debug logging to use the new internal Macro Deck 2 logging mechanism, but that will take some time. I will leave this issue open (pending) until I can do that and you can send me logs. Unless you tell me updating fixed your issue. Thanks!

**Comment by zedalert** [comment]
Since report everything was updated so many times, for now I also could not reproduce this bug. But I have another one:
1. Start Macro Deck with configured Discord plugin
2. Open it up and hover mouse over blinking Discord icon
3. Close Macro Deck and it will crash

**Comment by RecklessBoon** [comment]
thanks @zeda! I will close this issue and have opened a new one with your new report.
