### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by anschein** [RecklessBoon/Macro-Deck-Discord-Plugin#6]
I'm pretty sure everything set up right with video guide,but still can't connect to discord.
When I turn on debug the log says that:
> [ERROR]: Failed to process event! Error converting value {null} to type 'DiscordRPC.User+PremiumType'. Path 'user.premium_type'.
> [ERROR]: Data: {"cmd":"DISPATCH","data":{"v":1,"config":{"cdn_host":"cdn.discordapp.com","api_endpoint":"//discord.com/api","environment":"production"},"user":{"id":"*****","username":"*****","discriminator":"*****","avatar":"*****","bot":false,"flags":0,"premium_type":null}},"evt":"READY","nonce":null}

Is that means I need premium to use discord API?

**Comment by RecklessBoon** [comment]
Hi, 

First, no, you shouldn't need premium of any kind for this to work.

Second, I have recently gotten a few people contacting about this issue. 

One person had two accounts and only one of them had this error. It happened with an account that had never joined a server before. I think they fixed it by joining that account to a server at least once. They also mentioned that they had Nitro and no longer do on the account with an issue. 

Do either of those cases apply to your account? 

I'm trying to narrow down the issue since I can't replicate the issue.

**Comment by anschein** [comment]
> Hi,
> 
> First, no, you shouldn't need premium of any kind for this to work.
> 
> Second, I have recently gotten a few people contacting about this issue.
> 
> One person had two accounts and only one of them had this error. It happened with an account that had never joined a server before. I think they fixed it by joining that account to a server at least once. They also mentioned that they had Nitro and no longer do on the account with an issue.
> 
> Do either of those cases apply to your account?
> 
> I'm trying to narrow down the issue since I can't replicate the issue.

I have about ten servers in my discord so I think the first problem doesn't fit.And I never enable Nitro
The problem looks strange🤣

**Comment by ae9000** [comment]
I am having the exact same error when trying to first setup the plugin. It looks like it has something to do with the value that is sent for the account's premium status. Possibly it wants 0 1 or 2, and instead it is getting null?
(https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC/User.cs/)

**Comment by RecklessBoon** [comment]
All, I have put in a fix with the 3rd party library that should fix this.

https://github.com/Lachee/discord-rpc-csharp/pull/213

Once it is accepted and new version pushed to NuGet I will create an update here.

**Comment by Leondthurrell** [comment]
Having the same issue. Looking forward to the fix! thank you @RecklessBoon!

**Comment by RecklessBoon** [comment]
Fixed with release v1.1.11
