### ISSUE TITLE
Error after authorize app in discord

### ISSUE THREAD

**Issue by PinkLightCore** [RecklessBoon/Macro-Deck-Discord-Plugin#8]
[Discord Plugin] [Error] >> [ERROR]: Error occured during RecklessBoon.MacroDeck.Discord.RPC.RPCClient.SwapForToken()

**Comment by DodecaDev-LLC** [comment]
Is this issue still occurring on version 1.1.12?

**Comment by Seloodka** [comment]
I tested the plugin, it works correctly now :)
